'use client';

import { useState } from 'react';
import { ToolLayout } from '@/components/ToolLayout';
import { FAQSection } from '@/components/FAQSection';
import { generateSchemaMarkup } from '@/utils/seoCalculations';
import { SchemaResult } from '@/types';
import { SEO_TOOLS } from '@/lib/constants';
import { Database } from 'lucide-react';

export default function SchemaMarkupGeneratorPage() {
  const [schemaType, setSchemaType] = useState<'Article' | 'Product' | 'Organization' | 'WebSite' | 'FAQPage' | 'BreadcrumbList'>('Article');
  const [data, setData] = useState<Record<string, any>>({});
  const [result, setResult] = useState<SchemaResult | null>(null);

  const handleGenerate = () => {
    const calculatedResult = generateSchemaMarkup({
      type: schemaType,
      data,
    });
    setResult(calculatedResult);
  };

  const handleCopy = () => {
    if (result) {
      navigator.clipboard.writeText(result.jsonLd);
      alert('Schema JSON-LD copied to clipboard!');
    }
  };

  const updateDataField = (key: string, value: string) => {
    setData({
      ...data,
      [key]: value,
    });
  };

  const getFieldsForType = () => {
    switch (schemaType) {
      case 'Article':
        return ['headline', 'author', 'datePublished', 'dateModified', 'image'];
      case 'Product':
        return ['name', 'description', 'price', 'currency', 'availability', 'image'];
      case 'Organization':
        return ['name', 'url', 'logo', 'contactPoint', 'address'];
      case 'WebSite':
        return ['name', 'url', 'description'];
      case 'FAQPage':
        return ['mainEntity'];
      case 'BreadcrumbList':
        return ['itemListElement'];
      default:
        return [];
    }
  };

  const breadcrumbs = [
    { label: 'SEO Tools', href: '/seo-tools' },
    { label: 'Schema Markup Generator', href: '/tools/schema-markup-generator' },
  ];

  const relatedTools = SEO_TOOLS.filter(t => t.id !== 'schema-markup-generator');

  const faqs = [
    {
      question: 'What is schema markup?',
      answer: 'Schema markup (also called structured data) is code that helps search engines understand your content better. It can enable rich snippets in search results.',
    },
    {
      question: 'What are rich snippets?',
      answer: 'Rich snippets are enhanced search results that show additional information like ratings, prices, images, or FAQ answers directly in search results.',
    },
    {
      question: 'How do I add schema markup to my website?',
      answer: 'Add the JSON-LD code generated by this tool to the <head> section of your HTML page, or use Google Tag Manager to inject it.',
    },
    {
      question: 'Does schema markup improve rankings?',
      answer: 'Schema markup doesn\'t directly improve rankings, but it can improve click-through rates by making your results more attractive, and it helps search engines understand your content.',
    },
    {
      question: 'How do I test my schema markup?',
      answer: 'Use Google\'s Rich Results Test tool or Schema.org validator to test your schema markup and ensure it\'s valid.',
    },
  ];

  return (
    <ToolLayout 
      breadcrumbs={breadcrumbs} 
      relatedTools={relatedTools} 
      currentToolId="schema-markup-generator"
      seoTitle="Free Schema Markup Generator 2024 - Generate JSON-LD Structured Data | VoidToolbox"
      seoDescription="Free schema markup generator to create JSON-LD structured data for your website. Generate schema.org markup to enable rich snippets in search results."
      seoKeywords={[
        'schema markup generator',
        'structured data generator',
        'JSON-LD generator',
        'schema.org generator',
        'rich snippets generator',
        'schema generator',
        'free schema markup',
        'SEO schema generator',
      ]}
      faqs={faqs}
      toolName="Schema Markup Generator"
      toolDescription="Generate JSON-LD schema markup for structured data to improve your search engine visibility"
    >
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6 md:p-8">
        {/* Header */}
        <div className="flex items-center space-x-3 mb-6">
          <div className="p-3 bg-primary-100 dark:bg-primary-900 rounded-lg">
            <Database className="h-6 w-6 text-primary-600 dark:text-primary-400" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
              Schema Markup Generator
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              Generate JSON-LD structured data for your website
            </p>
          </div>
        </div>

        {/* Input Form */}
        <div className="space-y-6 mb-8">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Schema Type
            </label>
            <select
              value={schemaType}
              onChange={(e) => {
                setSchemaType(e.target.value as any);
                setData({});
              }}
              className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
            >
              <option value="Article">Article</option>
              <option value="Product">Product</option>
              <option value="Organization">Organization</option>
              <option value="WebSite">WebSite</option>
              <option value="FAQPage">FAQPage</option>
              <option value="BreadcrumbList">BreadcrumbList</option>
            </select>
          </div>

          <div className="space-y-4">
            {getFieldsForType().map((field) => (
              <div key={field}>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  {field.charAt(0).toUpperCase() + field.slice(1)}
                </label>
                <input
                  type="text"
                  value={data[field] || ''}
                  onChange={(e) => updateDataField(field, e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
                  placeholder={`Enter ${field}`}
                />
              </div>
            ))}
          </div>

          <button
            onClick={handleGenerate}
            className="w-full bg-primary-600 text-white py-3 px-6 rounded-lg font-medium hover:bg-primary-700 transition-colors"
          >
            Generate Schema Markup
          </button>
        </div>

        {/* Results */}
        {result && (
          <div className="animate-slide-in space-y-6">
            {/* Generated JSON-LD */}
            <div>
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold text-gray-900 dark:text-white">
                  Generated JSON-LD Schema
                </h3>
                <button
                  onClick={handleCopy}
                  className="px-4 py-2 bg-primary-600 text-white rounded-lg text-sm font-medium hover:bg-primary-700 transition-colors"
                >
                  Copy JSON-LD
                </button>
              </div>

              <div className="bg-gray-900 dark:bg-black rounded-lg p-6 overflow-x-auto">
                <pre className="text-green-400 font-mono text-sm whitespace-pre">
                  {result.jsonLd}
                </pre>
              </div>
            </div>

            {/* HTML Preview */}
            <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-6">
              <h3 className="font-semibold text-gray-900 dark:text-white mb-4">HTML Implementation</h3>
              <div className="bg-white dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-600">
                <code className="text-sm font-mono text-gray-900 dark:text-white whitespace-pre">
                  {result.preview}
                </code>
              </div>
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-4">
                Add this code to the &lt;head&gt; section of your HTML page.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Educational Content */}
      <div className="mt-8 prose prose-lg dark:prose-invert max-w-none">
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
          Understanding Schema Markup
        </h2>
        <p className="text-gray-600 dark:text-gray-400 mb-4">
          Schema markup helps search engines understand your content and can enable rich snippets 
          in search results, making your listings more attractive and informative.
        </p>
        <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
          Benefits of Schema Markup
        </h3>
        <ul className="list-disc list-inside text-gray-600 dark:text-gray-400 space-y-2">
          <li><strong>Rich Snippets:</strong> Enhanced search results with additional information</li>
          <li><strong>Better Understanding:</strong> Helps search engines understand your content</li>
          <li><strong>Higher CTR:</strong> More attractive results can improve click-through rates</li>
          <li><strong>Voice Search:</strong> Helps with voice search optimization</li>
          <li><strong>Knowledge Graph:</strong> Can help your business appear in Knowledge Graph</li>
        </ul>
      </div>

      {/* FAQ Section */}
      <FAQSection faqs={faqs} />
    </ToolLayout>
  );
}
